name: Generate Snake Animation

on:
  schedule:
    # Run workflow automatically every day at midnight
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual workflow runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks repo under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      
      # Generates the snake animation
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif
      
      # Push the generated files to the repository
      - name: Push changes
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: main
          message: 'Generate Snake Animation'
          add: 'dist'