name: Toggle Snake Animation Theme

# This workflow can be manually triggered
on:
  workflow_dispatch:
    inputs:
      theme:
        description: 'Theme to switch to (light/dark)'
        required: true
        default: 'dark'
        type: choice
        options:
        - light
        - dark

# Set permissions for the GITHUB_TOKEN
permissions:
  contents: write

jobs:
  toggle-theme:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
      
      # Generate the snake animation with the selected theme
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif
      
      # Update README to reflect current theme
      - name: Update README for theme
        run: |
          THEME="${{ github.event.inputs.theme }}"
          if [ "$THEME" = "dark" ]; then
            # Update README to show we're in dark mode and provide light mode button
            sed -i 's/Current Theme: Light/Current Theme: Dark/g' README.md
            sed -i 's/Switch to Dark Mode/Switch to Light Mode/g' README.md
            sed -i 's/workflow_dispatch\?theme=dark/workflow_dispatch\?theme=light/g' README.md
          else
            # Update README to show we're in light mode and provide dark mode button
            sed -i 's/Current Theme: Dark/Current Theme: Light/g' README.md
            sed -i 's/Switch to Light Mode/Switch to Dark Mode/g' README.md
            sed -i 's/workflow_dispatch\?theme=light/workflow_dispatch\?theme=dark/g' README.md
          fi
      
      # Commit and push changes
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Toggle snake animation theme to ${{ github.event.inputs.theme }}'
          file_pattern: 'dist/* README.md'
